"""
ERP React - Configuration Router
Endpoints for entreprise config, user management, and user profile.
Tables: entreprise_config, users (tenant schema).
"""

import json
import logging
import secrets as _secrets
from datetime import datetime

import requests as _requests
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from typing import Optional

from ..erp_auth import get_current_user, require_role, hash_password, ErpUser
from .. import erp_database as db
from .html_utils import (
    DEFAULT_DOCUMENT_THEME,
    THEME_KEYS,
    validate_document_theme,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/config", tags=["Configuration"])


# ============================================
# PYDANTIC MODELS
# ============================================

class ConfigValueUpdate(BaseModel):
    valeur: str


class UserCreate(BaseModel):
    username: str
    password: str
    email: Optional[str] = None
    full_name: Optional[str] = None
    role: str = "user"
    is_admin: bool = False


class UserUpdate(BaseModel):
    email: Optional[str] = None
    full_name: Optional[str] = None
    role: Optional[str] = None
    is_admin: Optional[bool] = None
    preferences_json: Optional[dict] = None


class PasswordChange(BaseModel):
    new_password: str


class ProfileUpdate(BaseModel):
    full_name: Optional[str] = None
    email: Optional[str] = None


# ============================================
# ENTREPRISE CONFIG
# ============================================

@router.get("/entreprise")
async def get_entreprise_config(user: ErpUser = Depends(get_current_user)):
    """Get all entreprise_config entries."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()

        # Check if table exists
        cursor.execute(
            "SELECT EXISTS (SELECT FROM information_schema.tables "
            "WHERE table_schema = %s AND table_name = 'entreprise_config')",
            (schema,),
        )
        exists = cursor.fetchone()
        if not exists or not exists.get("exists", False):
            return {"items": []}

        cursor.execute(
            "SELECT id, config_data, created_at, updated_at "
            "FROM entreprise_config ORDER BY id"
        )
        items = []
        for row in cursor.fetchall():
            items.append({
                "id": row["id"],
                "config_data": row.get("config_data"),
                "created_at": str(row["created_at"]) if row.get("created_at") else None,
                "updated_at": str(row["updated_at"]) if row.get("updated_at") else None,
            })
        return {"items": items}
    except Exception as exc:
        logger.error("get_entreprise_config error: %s", exc)
        return {"items": []}
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


# ============================================
# DOCUMENT COLOR THEME (soumission, facture, BC, BT, email)
# ============================================
#
# Tenant-wide color palette applied to every HTML document generated by
# the backend. Stored as a JSON value under the `document_theme` key of
# entreprise_config.config_data (same mechanism as logo_base64, company
# fields, etc.).

class DocumentThemeBody(BaseModel):
    """Partial theme body — missing keys fall back to defaults.

    Each value must be a hex color (#RGB or #RRGGBB). Unknown keys are
    silently dropped server-side by validate_document_theme.
    """
    primary: Optional[str] = None
    primary_dark: Optional[str] = None
    accent: Optional[str] = None
    accent_light: Optional[str] = None
    header_text: Optional[str] = None
    table_row_alt: Optional[str] = None
    info_bg: Optional[str] = None
    border: Optional[str] = None


@router.get("/document-theme")
async def get_document_theme_endpoint(user: ErpUser = Depends(get_current_user)):
    """Return the tenant's document color theme merged with defaults.

    Always succeeds — on any read error (missing table, corrupted JSON)
    the default Constructo palette is returned so the UI never breaks.
    """
    schema = user.schema
    if not schema:
        # Super-admin without tenant: return defaults
        return {"theme": dict(DEFAULT_DOCUMENT_THEME), "defaults": dict(DEFAULT_DOCUMENT_THEME)}

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        from .html_utils import get_document_theme as _get_theme
        merged = _get_theme(cursor)
        return {"theme": merged, "defaults": dict(DEFAULT_DOCUMENT_THEME)}
    except Exception as exc:
        logger.error("get_document_theme error: %s", exc)
        return {"theme": dict(DEFAULT_DOCUMENT_THEME), "defaults": dict(DEFAULT_DOCUMENT_THEME)}
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.put("/document-theme")
async def update_document_theme_endpoint(
    body: DocumentThemeBody,
    user: ErpUser = Depends(require_role("admin")),
):
    """Update the tenant's document color theme (admin only).

    Merges the request body into the current theme. To reset a single
    color to its default, the client should send the default value
    explicitly (frontend exposes a "Réinitialiser" button). An entirely
    empty body is a no-op.
    """
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    # Build dict from non-None fields and validate hex format
    provided = {k: v for k, v in body.model_dump().items() if v is not None}
    if not provided:
        return {"message": "Aucune modification", "theme": dict(DEFAULT_DOCUMENT_THEME)}
    try:
        validated = validate_document_theme(provided)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    # Only persist the keys the caller actually sent (normalized), not the
    # full merged palette — otherwise a partial update would overwrite any
    # defaults the user hadn't touched.
    to_store = {k: validated[k] for k in provided.keys() if k in validated}

    conn = db.get_conn()
    cursor = None
    # The pool hands out connections in AUTOCOMMIT — without toggling
    # autocommit off, `SELECT FOR UPDATE` releases its row lock as soon as
    # the SELECT statement commits, making the subsequent UPDATE racy
    # (two concurrent PUTs would overwrite each other's colors).
    prev_autocommit = conn.autocommit
    try:
        conn.autocommit = False
        db.set_tenant(conn, schema)
        cursor = conn.cursor()

        # Read current config (handles both text and jsonb column types).
        # With autocommit=False, FOR UPDATE holds the row lock until commit,
        # serializing concurrent PUTs against the same row.
        cursor.execute("SELECT config_data FROM entreprise_config WHERE id = 1 FOR UPDATE")
        row = cursor.fetchone()
        if row:
            raw = row.get("config_data")
            if isinstance(raw, dict):
                current = raw
            elif isinstance(raw, str) and raw.strip():
                try:
                    current = json.loads(raw)
                except (ValueError, TypeError):
                    current = {}
            else:
                current = {}
            existing_theme = current.get("document_theme") or {}
            if isinstance(existing_theme, str):
                try:
                    existing_theme = json.loads(existing_theme)
                except (ValueError, TypeError):
                    existing_theme = {}
            if not isinstance(existing_theme, dict):
                existing_theme = {}
            existing_theme.update(to_store)
            current["document_theme"] = existing_theme
            cursor.execute(
                "UPDATE entreprise_config SET config_data = %s, "
                "updated_at = CURRENT_TIMESTAMP WHERE id = 1",
                (json.dumps(current),),
            )
        else:
            current = {"document_theme": to_store}
            cursor.execute(
                "INSERT INTO entreprise_config (config_data, created_at, updated_at) "
                "VALUES (%s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (json.dumps(current),),
            )
        conn.commit()

        # Return the fully merged theme so the UI can refresh
        merged = dict(DEFAULT_DOCUMENT_THEME)
        merged.update(current.get("document_theme") or {})
        return {"message": "Thème de document mis à jour", "theme": merged}
    except HTTPException:
        try:
            conn.rollback()
        except Exception:
            pass
        raise
    except Exception as exc:
        logger.error("update_document_theme error: %s", exc)
        try:
            conn.rollback()
        except Exception:
            pass
        raise HTTPException(status_code=500, detail="Erreur lors de la mise à jour du thème")
    finally:
        if cursor:
            cursor.close()
        try:
            conn.autocommit = prev_autocommit
        except Exception:
            pass
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.delete("/document-theme")
async def reset_document_theme_endpoint(
    user: ErpUser = Depends(require_role("admin")),
):
    """Reset the tenant's document color theme to defaults (admin only).

    Removes the `document_theme` key from entreprise_config.config_data,
    so subsequent reads fall back to DEFAULT_DOCUMENT_THEME.
    """
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    prev_autocommit = conn.autocommit
    try:
        conn.autocommit = False
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        cursor.execute("SELECT config_data FROM entreprise_config WHERE id = 1 FOR UPDATE")
        row = cursor.fetchone()
        if row:
            raw = row.get("config_data")
            if isinstance(raw, dict):
                current = raw
            elif isinstance(raw, str) and raw.strip():
                try:
                    current = json.loads(raw)
                except (ValueError, TypeError):
                    current = {}
            else:
                current = {}
            if "document_theme" in current:
                current.pop("document_theme", None)
                cursor.execute(
                    "UPDATE entreprise_config SET config_data = %s, "
                    "updated_at = CURRENT_TIMESTAMP WHERE id = 1",
                    (json.dumps(current),),
                )
        conn.commit()
        return {"message": "Thème réinitialisé", "theme": dict(DEFAULT_DOCUMENT_THEME)}
    except HTTPException:
        try:
            conn.rollback()
        except Exception:
            pass
        raise
    except Exception as exc:
        logger.error("reset_document_theme error: %s", exc)
        try:
            conn.rollback()
        except Exception:
            pass
        raise HTTPException(status_code=500, detail="Erreur lors de la réinitialisation du thème")
    finally:
        if cursor:
            cursor.close()
        try:
            conn.autocommit = prev_autocommit
        except Exception:
            pass
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.put("/entreprise/{cle}")
async def update_entreprise_config(
    cle: str,
    body: ConfigValueUpdate,
    user: ErpUser = Depends(require_role("admin")),
):
    """Update an entreprise_config value (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    prev_autocommit = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        # FIX P1 (round 9): forcer autocommit=False pour que SELECT FOR UPDATE
        # tienne son lock pendant le merge JSON + UPDATE. En autocommit (defaut
        # pool), 2 PUT concurrents perdent des modifications (last-write-wins).
        try:
            prev_autocommit = conn.autocommit
        except Exception:
            prev_autocommit = None
        try:
            conn.autocommit = False
        except Exception:
            pass
        # Read current config (handles both text and jsonb column types)
        cursor.execute("SELECT config_data FROM entreprise_config WHERE id = 1 FOR UPDATE")
        row = cursor.fetchone()
        if row:
            raw = row.get("config_data")
            if isinstance(raw, dict):
                current = raw
            elif isinstance(raw, str) and raw.strip():
                current = json.loads(raw)
            else:
                current = {}
            current[cle] = body.valeur
            cursor.execute(
                "UPDATE entreprise_config SET config_data = %s, "
                "updated_at = CURRENT_TIMESTAMP WHERE id = 1 RETURNING id",
                (json.dumps(current),),
            )
            row = cursor.fetchone()
        else:
            cursor.execute(
                "INSERT INTO entreprise_config (config_data, created_at, updated_at) "
                "VALUES (%s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) RETURNING id",
                (json.dumps({cle: body.valeur}),),
            )
            row = cursor.fetchone()
        conn.commit()
        return {"message": "Configuration mise à jour", "id": row["id"] if row else 0}
    except HTTPException:
        try:
            conn.rollback()
        except Exception:
            pass
        raise
    except Exception as exc:
        logger.error("update_entreprise_config error: %s", exc)
        try:
            conn.rollback()
        except Exception:
            pass
        raise HTTPException(status_code=500, detail="Erreur lors de la mise à jour")
    finally:
        # Restaurer l'autocommit avant retour au pool.
        if prev_autocommit is not None:
            try:
                conn.autocommit = prev_autocommit
            except Exception:
                pass
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


# ============================================
# USERS MANAGEMENT (admin only)
# ============================================

@router.get("/users")
async def list_users(user: ErpUser = Depends(require_role("admin"))):
    """List all users in the tenant (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        cursor.execute(
            "SELECT id, username, email, "
            "COALESCE(full_name, '') as full_name, "
            "role, COALESCE(is_admin, FALSE) as is_admin, "
            "COALESCE(active, TRUE) as active, employee_id, preferences_json, "
            "last_login, created_at "
            "FROM users ORDER BY created_at DESC"
        )
        items = []
        for row in cursor.fetchall():
            items.append({
                "id": row["id"],
                "username": row["username"],
                "email": row.get("email", ""),
                "full_name": row.get("full_name", ""),
                "role": row.get("role", "user"),
                "is_admin": row.get("is_admin", False),
                "active": row.get("active", True),
                "employee_id": row.get("employee_id"),
                "preferences_json": row.get("preferences_json"),
                "last_login": str(row["last_login"]) if row.get("last_login") else None,
                "created_at": str(row["created_at"]) if row.get("created_at") else None,
            })
        return {"items": items, "total": len(items)}
    except Exception as exc:
        logger.error("list_users error: %s", exc)
        return {"items": [], "total": 0}
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.post("/users")
async def create_user(
    body: UserCreate,
    user: ErpUser = Depends(require_role("admin")),
):
    """Create a new user (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    if len(body.password) < 6:
        raise HTTPException(status_code=400, detail="Le mot de passe doit avoir au moins 6 caracteres")

    password_hash = hash_password(body.password)

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()

        # Check for duplicate username
        cursor.execute("SELECT id FROM users WHERE username = %s", (body.username,))
        if cursor.fetchone():
            raise HTTPException(status_code=409, detail="Ce nom d'utilisateur existe deja")

        cursor.execute(
            "INSERT INTO users (username, password_hash, email, full_name, role, is_admin, active, created_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, TRUE, CURRENT_TIMESTAMP) RETURNING id",
            (body.username, password_hash, body.email, body.full_name,
             body.role, body.is_admin),
        )
        row = cursor.fetchone()
        conn.commit()
        return {"id": row["id"] if row else 0, "message": "Utilisateur créé avec succès"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("create_user error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors de la création de l'utilisateur")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.put("/users/{user_id}")
async def update_user(
    user_id: int,
    body: UserUpdate,
    user: ErpUser = Depends(require_role("admin")),
):
    """Update a user (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()

        # Build dynamic update
        updates = []
        params = []
        if body.email is not None:
            updates.append("email = %s")
            params.append(body.email)
        if body.full_name is not None:
            updates.append("full_name = %s")
            params.append(body.full_name)
        if body.role is not None:
            updates.append("role = %s")
            params.append(body.role)
        if body.is_admin is not None:
            updates.append("is_admin = %s")
            params.append(body.is_admin)
        if body.preferences_json is not None:
            updates.append("preferences_json = %s::jsonb")
            params.append(json.dumps(body.preferences_json))

        if not updates:
            return {"message": "Aucune modification"}

        params.append(user_id)
        query = f"UPDATE users SET {', '.join(updates)} WHERE id = %s RETURNING id"
        cursor.execute(query, tuple(params))
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Utilisateur non trouvé")
        conn.commit()
        return {"message": "Utilisateur mis à jour"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("update_user error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors de la mise à jour")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.put("/users/{user_id}/password")
async def change_user_password(
    user_id: int,
    body: PasswordChange,
    user: ErpUser = Depends(get_current_user),
):
    """Change a user's password (admin or self)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    # Only admin can change other users' passwords
    if user.user_id != user_id and user.role != "admin" and user.user_type != "super_admin":
        raise HTTPException(status_code=403, detail="Acces refuse")

    if len(body.new_password) < 6:
        raise HTTPException(status_code=400, detail="Le mot de passe doit avoir au moins 6 caracteres")

    password_hash = hash_password(body.new_password)

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE users SET password_hash = %s WHERE id = %s RETURNING id",
            (password_hash, user_id),
        )
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Utilisateur non trouvé")
        conn.commit()
        return {"message": "Mot de passe mis à jour"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("change_user_password error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors du changement de mot de passe")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.delete("/users/{user_id}")
async def deactivate_user(
    user_id: int,
    user: ErpUser = Depends(require_role("admin")),
):
    """Deactivate a user (admin only, set active=false)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    if user.user_id == user_id:
        raise HTTPException(status_code=400, detail="Vous ne pouvez pas vous desactiver vous-meme")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE users SET active = FALSE WHERE id = %s RETURNING id",
            (user_id,),
        )
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Utilisateur non trouvé")
        conn.commit()
        return {"message": "Utilisateur desactive"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("deactivate_user error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors de la desactivation")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


# ============================================
# USER PROFILE (self)
# ============================================

@router.get("/profile")
async def get_profile(user: ErpUser = Depends(get_current_user)):
    """Get current user profile."""
    schema = user.schema
    if not schema:
        # Super-admin fallback
        return {
            "id": user.user_id,
            "username": user.display_name,
            "email": user.email,
            "full_name": "",
            "role": user.role,
            "is_admin": user.user_type == "super_admin",
        }

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        cursor.execute(
            "SELECT id, username, email, "
            "COALESCE(full_name, '') as full_name, "
            "role, COALESCE(is_admin, FALSE) as is_admin, last_login "
            "FROM users WHERE id = %s",
            (user.user_id,),
        )
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Profil non trouvé")
        return {
            "id": row["id"],
            "username": row["username"],
            "email": row.get("email", ""),
            "full_name": row.get("full_name", ""),
            "role": row.get("role", "user"),
            "is_admin": row.get("is_admin", False),
            "last_login": str(row["last_login"]) if row.get("last_login") else None,
        }
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("get_profile error: %s", exc)
        raise HTTPException(status_code=500, detail="Erreur lors du chargement du profil")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.put("/profile")
async def update_profile(
    body: ProfileUpdate,
    user: ErpUser = Depends(get_current_user),
):
    """Update own profile (full_name, email)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()

        updates = []
        params = []
        if body.full_name is not None:
            updates.append("full_name = %s")
            params.append(body.full_name)
        if body.email is not None:
            updates.append("email = %s")
            params.append(body.email)

        if not updates:
            return {"message": "Aucune modification"}

        params.append(user.user_id)
        query = f"UPDATE users SET {', '.join(updates)} WHERE id = %s RETURNING id"
        cursor.execute(query, tuple(params))
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Profil non trouvé")
        conn.commit()
        return {"message": "Profil mis à jour"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("update_profile error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors de la mise à jour du profil")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


# ============================================
# WEBHOOKS MANAGEMENT
# ============================================

class WebhookCreate(BaseModel):
    url: str
    events: list = []
    secret: Optional[str] = None
    description: Optional[str] = None


class WebhookUpdate(BaseModel):
    url: Optional[str] = None
    events: Optional[list] = None
    secret: Optional[str] = None
    description: Optional[str] = None
    active: Optional[bool] = None


def _ensure_webhook_tables(cursor):
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS webhooks (
            id SERIAL PRIMARY KEY,
            entreprise_id INTEGER,
            url TEXT NOT NULL,
            events TEXT[] DEFAULT '{}',
            secret TEXT,
            active BOOLEAN DEFAULT TRUE,
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    # Defensive migration: older tenant schemas may pre-date several columns
    # that were added to the CREATE TABLE above. On ancient tenants the
    # `entreprise_id` column is NOT NULL (legacy schema), so we populate it
    # in the INSERT below rather than relying on a default.
    for col_name, col_type in (
        ("entreprise_id", "INTEGER"),
        ("events", "TEXT[] DEFAULT '{}'"),
        ("secret", "TEXT"),
        ("active", "BOOLEAN DEFAULT TRUE"),
        ("description", "TEXT"),
        ("created_at", "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"),
        ("updated_at", "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"),
    ):
        try:
            cursor.execute(f"ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS {col_name} {col_type}")
        except Exception as exc:
            logger.warning("defensive ALTER webhooks.%s failed: %s", col_name, exc)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS webhook_deliveries (
            id SERIAL PRIMARY KEY,
            webhook_id INTEGER NOT NULL,
            event_type TEXT NOT NULL,
            payload JSONB,
            response_status INTEGER,
            response_body TEXT,
            success BOOLEAN DEFAULT FALSE,
            delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)


@router.get("/webhooks")
async def list_webhooks(user: ErpUser = Depends(require_role("admin"))):
    """List all webhooks (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        _ensure_webhook_tables(cursor)
        conn.commit()

        cursor.execute("SELECT * FROM webhooks ORDER BY created_at DESC")
        items = []
        for row in cursor.fetchall():
            items.append({
                "id": row["id"],
                "url": row["url"],
                "events": row.get("events", []),
                "secret": ("..." + row["secret"][-4:]) if row.get("secret") else None,
                "active": row.get("active", True),
                "description": row.get("description"),
                "created_at": str(row["created_at"]) if row.get("created_at") else None,
                "updated_at": str(row["updated_at"]) if row.get("updated_at") else None,
            })
        return {"items": items}
    except Exception as exc:
        logger.error("list_webhooks error: %s", exc)
        return {"items": []}
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.post("/webhooks")
async def create_webhook(body: WebhookCreate, user: ErpUser = Depends(require_role("admin"))):
    """Create a new webhook (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    secret = body.secret or _secrets.token_urlsafe(32)

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        _ensure_webhook_tables(cursor)

        # Resolve the tenant entreprise_id from the schema so legacy tenants
        # with NOT NULL on webhooks.entreprise_id don't crash the INSERT.
        # ErpUser doesn't expose entreprise_id directly, but the schema
        # matches `entreprises.slug` exactly.
        entreprise_id = None
        try:
            cursor.execute(
                "SELECT id FROM public.entreprises WHERE slug = %s",
                (schema,),
            )
            ent_row = cursor.fetchone()
            if ent_row:
                entreprise_id = ent_row["id"]
        except Exception as exc:
            logger.warning("webhook entreprise_id lookup failed: %s", exc)

        if entreprise_id is None:
            # Legacy tenants have NOT NULL on webhooks.entreprise_id. Refuse
            # early with a clear 500 instead of crashing on the INSERT.
            raise HTTPException(
                status_code=500,
                detail="Impossible de resoudre l'entreprise pour ce tenant",
            )

        cursor.execute(
            "INSERT INTO webhooks (entreprise_id, url, events, secret, description) "
            "VALUES (%s, %s, %s::text[], %s, %s) RETURNING id",
            (entreprise_id, body.url, body.events, secret, body.description),
        )
        row = cursor.fetchone()
        conn.commit()
        return {"id": row["id"] if row else 0, "secret": secret, "message": "Webhook créé"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("create_webhook error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors de la création du webhook")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.put("/webhooks/{webhook_id}")
async def update_webhook(webhook_id: int, body: WebhookUpdate, user: ErpUser = Depends(require_role("admin"))):
    """Update a webhook (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        _ensure_webhook_tables(cursor)

        updates = []
        params = []
        if body.url is not None:
            updates.append("url = %s")
            params.append(body.url)
        if body.events is not None:
            updates.append("events = %s::text[]")
            params.append(body.events)
        if body.secret is not None:
            updates.append("secret = %s")
            params.append(body.secret)
        if body.description is not None:
            updates.append("description = %s")
            params.append(body.description)
        if body.active is not None:
            updates.append("active = %s")
            params.append(body.active)

        if not updates:
            return {"message": "Aucune modification"}

        updates.append("updated_at = CURRENT_TIMESTAMP")
        params.append(webhook_id)
        query = f"UPDATE webhooks SET {', '.join(updates)} WHERE id = %s RETURNING id"
        cursor.execute(query, tuple(params))
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Webhook non trouvé")
        conn.commit()
        return {"message": "Webhook mis à jour"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("update_webhook error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors de la mise à jour du webhook")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.delete("/webhooks/{webhook_id}")
async def delete_webhook(webhook_id: int, user: ErpUser = Depends(require_role("admin"))):
    """Delete a webhook (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        _ensure_webhook_tables(cursor)

        cursor.execute("DELETE FROM webhooks WHERE id = %s RETURNING id", (webhook_id,))
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Webhook non trouvé")
        conn.commit()
        return {"message": "Webhook supprimé"}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("delete_webhook error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors de la suppression du webhook")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.post("/webhooks/{webhook_id}/test")
async def test_webhook(webhook_id: int, user: ErpUser = Depends(require_role("admin"))):
    """Send a test ping to a webhook (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        _ensure_webhook_tables(cursor)

        cursor.execute("SELECT id, url FROM webhooks WHERE id = %s", (webhook_id,))
        row = cursor.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Webhook non trouvé")

        webhook_url = row["url"]
        payload = {
            "event": "test.ping",
            "timestamp": datetime.now().isoformat(),
            "test": True,
        }

        success = False
        status_code = None
        response_body = None
        message = ""

        try:
            resp = _requests.post(webhook_url, json=payload, timeout=10)
            status_code = resp.status_code
            response_body = resp.text[:2000] if resp.text else ""
            success = 200 <= resp.status_code < 300
            message = "Test envoye avec succes" if success else f"Le serveur a repondu avec le code {status_code}"
        except _requests.exceptions.ConnectionError:
            message = "Impossible de se connecter au serveur"
        except _requests.exceptions.Timeout:
            message = "Le serveur n'a pas repondu dans le delai imparti"
        except _requests.exceptions.RequestException as req_exc:
            message = f"Erreur lors de l'envoi: {str(req_exc)}"

        # Record delivery
        cursor.execute(
            "INSERT INTO webhook_deliveries (webhook_id, event_type, payload, response_status, response_body, success) "
            "VALUES (%s, %s, %s::jsonb, %s, %s, %s)",
            (webhook_id, "test.ping", json.dumps(payload), status_code, response_body, success),
        )
        conn.commit()

        return {"success": success, "status_code": status_code, "message": message}
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("test_webhook error: %s", exc)
        conn.rollback()
        raise HTTPException(status_code=500, detail="Erreur lors du test du webhook")
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()


@router.get("/webhooks/{webhook_id}/deliveries")
async def list_webhook_deliveries(
    webhook_id: int,
    user: ErpUser = Depends(require_role("admin")),
    limit: int = Query(20, ge=1, le=100),
):
    """Get delivery history for a webhook (admin only)."""
    schema = user.schema
    if not schema:
        raise HTTPException(status_code=400, detail="Contexte entreprise requis")

    conn = db.get_conn()
    cursor = None
    try:
        db.set_tenant(conn, schema)
        cursor = conn.cursor()
        _ensure_webhook_tables(cursor)

        cursor.execute(
            "SELECT * FROM webhook_deliveries WHERE webhook_id = %s "
            "ORDER BY delivered_at DESC LIMIT %s",
            (webhook_id, limit),
        )
        items = []
        for row in cursor.fetchall():
            items.append({
                "id": row["id"],
                "webhook_id": row["webhook_id"],
                "event_type": row["event_type"],
                "payload": row.get("payload"),
                "response_status": row.get("response_status"),
                "response_body": row.get("response_body"),
                "success": row.get("success", False),
                "delivered_at": str(row["delivered_at"]) if row.get("delivered_at") else None,
            })
        return {"items": items}
    except Exception as exc:
        logger.error("list_webhook_deliveries error: %s", exc)
        return {"items": []}
    finally:
        if cursor:
            cursor.close()
        try:
            db.reset_tenant(conn)
        except Exception:
            pass
        conn.close()
